[package]
name = "openerapp"
version = "3.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
ash = { version = "0.38", features = ["loaded", "debug", "std"] }
ash-window = "0.13.0"
winit = { version = "0.30", features = ["rwh_06"] }
thiserror = "2.0"
